---
language: python
services: docker

env:
  global:
    - MOLECULE_NO_LOG: "false"
  matrix:
    - MOLECULE_DISTRO: ubuntu:18.04
    - MOLECULE_DISTRO: ubuntu:16.04

install:
  # Install test dependencies.
  - pip install molecule docker ansible-lint flake8 testinfra

before_script:
  - cd ../ && mv ansible-turtl juju4.turtl
  - cd juju4.turtl
  - ansible-galaxy install -p .. -r requirements.yml

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
