---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
  - name: Example assertion
    assert:
      that: true
  - name: Ensure config file is present
    stat:
      path: /var/www-turtl/src/config/config.yaml
    register: cfg
  - name: Validate config present
    assert:
      that: cfg.stat.exists and cfg.stat.size != 0
  - name: Ensure process is running
    command: pgrep -u www-turtl nodejs
    register: ps
    changed_when: false
  - name: Validate ps output
    assert:
      that: ps.stdout
  - name: Ensure port is listening
    wait_for:
      host: localhost
      port: 8181
  - name: check if turtl answering network
    uri:
      url: http://localhost:8181
    register: web
  - debug: web
  - name: Validate network request output
    assert:
      that: web.json.greeting == 'Hi.'
